### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by nikolay** [arminhammer/wolkenkratzer#1]
The documentation talks about `addParameter()`, `addMapping()`, and `addOutput()`, which are now undefined.

**Comment by arminhammer** [comment]
Good catch. I consolidated those calls into Template.add() recently, and I'm checking the type of the input to determine where to add it. I tried to update all mentions of this in the documentation.

I saw one mention of addMapping in the README, which I just fixed. Are there mentions elsewhere that I'm missing? Let me know and I'll update them.

**Comment by arminhammer** [comment]
Nevermind, just realized that my gh-pages branch was not being updated when I pushed new releases. Looking into how I can keep it up to date now. For now I recommend looking at the repo project README, as that should have the most up-to-date documentation.

**Comment by arminhammer** [comment]
Documentation is updated now and up to date with 0.4.10.

**Comment by nikolay** [comment]
Thank you, @arminhammer!
